on:
  workflow_call:

name: pypi_publish

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # This permission is needed for PRIVATE REPOS
      contents: read
      # This permission is needed for TRUSTED PUBLISHING
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
      - name: Publish package distributions to PyPI
        run: pdm publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
